

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/usrun?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false&useUnicode=yes&characterEncoding=utf8&characterResultSets=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_USERNAME:password}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  auth:
    tokenSecret: ${TOKEN_SECRECT}
    tokenExpirationMs: ${TOKEN_EXPIRATION}
  oauth2:
    google:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRECT}
      scopes:
        - email
        - profile
server:
  port: ${PORT:8080}
